files:
  - name: some_file
    file: file.txt
    actions:
      - download
  - name: neasted_archive
    file: archive.zip
    actions:
      - download
      - unpack
  - name: inner_archive
    file: inner.7z
    actions:
      - unpack
    dependencies:
      - neasted_archive

host: "http://127.0.0.1:5000"
target: "/api/files/"
