files:
  - my_pretty_archive:
    file: archive.zip
    actions:
      - download
      - unpack
  - my_text_file:
    file: text_file
    actions:
      - download
  - my_internal_archive:
    file: internal.7z
    actions:
      - unpack
    dependencies:
      - my_pretty_archive

host: "http://127.0.0.1:5000"
target: "/api/files/"
